# Scripts Programs
$clipboard = ~/.config/rofi/clipboard/launcher.sh
$music = ~/.config/rofi/musicPlayer/music-player.sh

# Apps
$terminal = kitty
$browser = zen-browser
$fileManager = nautilus
$notes = Logseq
