#░█▀▀░▀█▀░█▀█░█▀▄░▀█▀░█░█░█▀█
#░▀▀█░░█░░█▀█░█▀▄░░█░░█░█░█▀▀
#░▀▀▀░░▀░░▀░▀░▀░▀░░▀░░▀▀▀░▀░░


# Autostarts
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-clip-persist --clipboard regular
exec-once = /usr/lib/polkit-kde-authentication-agent-1
#exec-once = hyprpm reload -n
exec-once = pypr
exec-once = awww-daemon
exec-once = swayosd-server --top-margin 0.99
exec-once = wlsunset -l 20.5 -L 78.9 # Night Light

# Battery notifications (Warning at 30%, Critical at 15%)
exec-once = batsignal -n BAT0 -w 30 -c 15

# Launch core background apps individually
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = sleep 2 && /home/suju/.local/bin/waypaper --restore
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# Charging Sound Script
exec-once = ~/.config/scripts/charger-sound.sh &

# Handle the idle daemon
exec-once = killall -q hypridle; hypridle
