#░█▀▄░█░█░█░░░█▀▀░█▀▀
#░█▀▄░█░█░█░░░█▀▀░▀▀█
#░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀

# ----------------------------------------------------- 
# Window Rules (Fixed Sizes with Math)
# ----------------------------------------------------- 

# Opacity Rule
windowrule = match:class kitty, opacity 1 0.8
windowrule = match:class thunar, opacity 1 0.6


# XWayland Video Bridge
windowrule = match:class xwaylandvideobridge, opacity 0.0 override 0.0 override
windowrule = match:class xwaylandvideobridge, no_anim on
windowrule = match:class xwaylandvideobridge, no_focus on
windowrule = match:class xwaylandvideobridge, no_initial_focus on

# MPV
windowrule = match:class mpv, float on
windowrule = match:class mpv, center on
windowrule = match:class mpv, size (monitor_w*0.65) (monitor_h*0.75)

# Pavucontrol
windowrule = match:class pavucontrol, float on
windowrule = match:class pavucontrol, center on
windowrule = match:class pavucontrol, size (monitor_w*0.45) (monitor_h*0.65)

# Waypaper
windowrule = match:class waypaper, float on
windowrule = match:class waypaper, center on
windowrule = match:class waypaper, size (monitor_w*0.65) (monitor_h*0.65)

# Thunar
windowrule = match:class thunar, float on
windowrule = match:class thunar, center on
windowrule = match:class thunar, size (monitor_w*0.65) (monitor_h*0.65)

# Image Viewer EOG
windowrule = match:class org.gnome.eog, float on
windowrule = match:class org.gnome.eog, center on
windowrule = match:class org.gnome.eog, size (monitor_w*0.75) (monitor_h*0.75)

# Qalculate
windowrule = match:class qalculate-gtk, float on
windowrule = match:class qalculate-gtk, center on
windowrule = match:class qalculate-gtk, size (monitor_w*0.6) (monitor_h*0.6)

#Waydroid
windowrule = match:class Waydroid, float on
windowrule = match:class Waydroid, center on
windowrule = match:class Waydroid, size (monitor_w*0.5) (monitor_h*0.95)

#LocalSend
windowrule = match:class localsend, float on
windowrule = match:class localsend, center on
windowrule = match:class localsend, size (monitor_w*0.4) (monitor_h*0.85)

#Steam
windowrule = match:class steam, float on
windowrule = match:class steam, center on
windowrule = match:class steam, size (monitor_w*0.85) (monitor_h*0.75)

#Pavucontrol
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.pulseaudio.pavucontrol, center on
windowrule = match:class org.pulseaudio.pavucontrol, size (monitor_w*0.85) (monitor_h*0.75)

#Bluemam
windowrule = match:class blueman-manager, float on
windowrule = match:class blueman-manager, center on
windowrule = match:class blueman-manager, size (monitor_w*0.35) (monitor_h*0.75)

#Blurs
layerrule = blur on, ignore_alpha 0.1, match:namespace logout_dialog
layerrule = blur on, ignore_alpha 0.1, match:namespace swayosd
layerrule = blur on, ignore_alpha 0.1, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.1, match:namespace swaync-notification-window
layerrule = blur on, ignore_alpha 0.1, match:namespace rofi

#Steam Games
windowrule = match:class ^steam_app_.*, fullscreen on

# GTK File Dialogs (Floating & Centered)
windowrule = float on, match:title ^(Open File)$
windowrule = size 800 600, match:title ^(Open File)$
windowrule = center on, match:title ^(Open File)$

windowrule = float on, match:title ^(Select a File)$
windowrule = float on, match:title ^(Choose Folder)$
windowrule = float on, match:title ^(Save As)$

# Portal & System Dialogs
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:class ^(org.freedesktop.impl.portal.desktop.gtk)$

# Also center and set size
windowrule = float on, match:class zen, match:title Picture-in-Picture
windowrule = size 748 500, match:class zen, match:title Picture-in-Picture
